micronaut:
  application:
    name: oda-twitch-service
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: https://auth.oda.digital/realms/ODA/protocol/openid-connect/certs
logger:
  levels:
    io.github.opendonationassistant: INFO
twitch:
  client:
    id: ${TWITCH_CLIENT_ID}
    secret: ${TWITCH_CLIENT_SECRET}
